// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOVzA6IxP1fiwcvXmQw6Hs-C_1mreFh4',
    appId: '1:759265755482:web:e0064e0a175ddac1093363',
    messagingSenderId: '759265755482',
    projectId: 'garabu-a20b5',
    authDomain: 'garabu-a20b5.firebaseapp.com',
    storageBucket: 'garabu-a20b5.firebasestorage.app',
    measurementId: 'G-7JY8KY3NXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUJwpWVAAHGkE4rIvy0EO3LhTDo8PiEw',
    appId: '1:759265755482:android:1ba96d50080874ba093363',
    messagingSenderId: '759265755482',
    projectId: 'garabu-a20b5',
    storageBucket: 'garabu-a20b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQhIXFDY59S5gjIua6ZpZx2X8uC8Rz0aQ',
    appId: '1:759265755482:ios:8dc49c2e0179f317093363',
    messagingSenderId: '759265755482',
    projectId: 'garabu-a20b5',
    storageBucket: 'garabu-a20b5.firebasestorage.app',
    iosClientId: '759265755482-3pojn06fsj3nsk7dfsgvhiv3988a9qnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.garabu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQhIXFDY59S5gjIua6ZpZx2X8uC8Rz0aQ',
    appId: '1:759265755482:ios:8dc49c2e0179f317093363',
    messagingSenderId: '759265755482',
    projectId: 'garabu-a20b5',
    storageBucket: 'garabu-a20b5.firebasestorage.app',
    iosClientId: '759265755482-3pojn06fsj3nsk7dfsgvhiv3988a9qnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.garabu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxOVzA6IxP1fiwcvXmQw6Hs-C_1mreFh4',
    appId: '1:759265755482:web:c5f0fafbcd68d400093363',
    messagingSenderId: '759265755482',
    projectId: 'garabu-a20b5',
    authDomain: 'garabu-a20b5.firebaseapp.com',
    storageBucket: 'garabu-a20b5.firebasestorage.app',
    measurementId: 'G-P463631MB9',
  );
}
